project:
  type: book
  title: "*Clostridoides difficile* comprehensive overview"

editor: visual

book:
  title: "*Clostridoides difficile* Profiling"
  author: "Kah Yen Claire Yeak"

  chapters:
    - preface.qmd
    - index.qmd
    - chapter_2.qmd
    - chapter_3.qmd
    - chapter_4.qmd
    - chapter_5.qmd
    - chapter_6.qmd
    - chapter_7.qmd
    - reference.qmd


format:
  html:
    theme: flatly  #preferred theme
    toc: true  # Display a table of contents
    toc-depth: 2  # Set the depth of the table of contents
    number-sections: true  # Number the sections of your book
    css: styles.css  # Optional custom CSS for styling
    bibliography: references.bib  # Link to your bibliography file
    include-after-body: footer.html  # Add custom footer
